routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\DataArtikelController;
use App\Http\Controllers\DataGejalaController;
use App\Http\Controllers\DataJadwalPeriksaController;
use App\Http\Controllers\DataPenyakitController;
use App\Http\Controllers\DataRiwayatDiagnosaController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function(){
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'store'])->name('store');
});

Route::middleware(['auth', 'isAdmin'])->group(function(){
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/', BerandaController::class)->name('beranda');

    Route::group(['prefix' => 'data-penyakit', 'as' => 'data-penyakit.'], function() {
        Route::get('/', [DataPenyakitController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataPenyakitController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataPenyakitController::class, 'store'])->name('store');
        Route::get('/{dataPenyakit}/edit', [DataPenyakitController::class, 'edit'])->name('edit');
        Route::put('/{dataPenyakit}/edit', [DataPenyakitController::class, 'update'])->name('update');
        Route::delete('/{dataPenyakit}/delete', [DataPenyakitController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-gejala', 'as' => 'data-gejala.'], function(){
        Route::get('/', [DataGejalaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataGejalaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataGejalaController::class, 'store'])->name('store');
        Route::get('/{dataGejala}/edit', [DataGejalaController::class, 'edit'])->name('edit');
        Route::put('/{dataGejala}/edit', [DataGejalaController::class, 'update'])->name('update');
        Route::delete('/{dataGejala}/delete', [DataGejalaController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-jadwal-periksa', 'as' => 'data-jadwal-periksa.'], function() {
        Route::get('/', [DataJadwalPeriksaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataJadwalPeriksaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataJadwalPeriksaController::class, 'store'])->name('store');
        Route::delete('/{dataJadwalPeriksa}/delete', [DataJadwalPeriksaController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-riwayat-diagnosa', 'as' => 'data-riwayat-diagnosa.'], function() {
        Route::get('/', [DataRiwayatDiagnosaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataRiwayatDiagnosaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataRiwayatDiagnosaController::class, 'store'])->name('store');
        Route::get('/{dataRiwayatDiagnosa}/detail', [DataRiwayatDiagnosaController::class, 'show'])->name('show');
        Route::get('/{dataRiwayatDiagnosa}/pdf', [DataRiwayatDiagnosaController::class, 'pdf'])->name('pdf');
    });

    Route::group(['prefix' => 'data-artikel', 'as' => 'data-artikel.'], function() {
        Route::get('/', [DataArtikelController::class, 'index'])->name('index');
        Route::get('/create', [DataArtikelController::class, 'create'])->name('create');
        Route::post('/create', [DataArtikelController::class, 'store'])->name('store');
        Route::get('/{dataArtikel}/edit', [DataArtikelController::class, 'edit'])->name('edit');
        Route::put('/{dataArtikel}/edit', [DataArtikelController::class, 'update'])->name('update');
        Route::delete('/{dataArtikel}/delete', [DataArtikelController::class, 'destroy'])->name('destroy');
    });
});

app/Models/DataGejala.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DataGejala extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
    protected $table = 'data_gejala';
}

app/Http/Controllers/DataGejalaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DataGejalaRequest;
use App\Models\DataGejala;
use Illuminate\Http\Request;

class DataGejalaController extends Controller
{
    public function index()
    {
        $dataGejala = DataGejala::latest()->get();

        return view('admin.data-gejala.index', compact('dataGejala'));
    }

    public function create()
    {
        return view('admin.data-gejala.create');
    }

    public function store(DataGejalaRequest $request)
    {
        DataGejala::create($request->all());

        return redirect()->route('data-gejala.index')->with('success', 'Data Berhasil Ditambahkan!');
    }

    public function edit(DataGejala $dataGejala)
    {
        return view('admin.data-gejala.edit', compact('dataGejala'));
    }

    public function update(DataGejalaRequest $request, DataGejala $dataGejala)
    {
        $dataGejala->update($request->all());

        return redirect()->route('data-gejala.index')->with('update', 'Data Berhasil Diupdate!');
    }

    public function destroy(DataGejala $dataGejala)
    {
        $dataGejala->delete();

        return redirect()->route('data-gejala.index')->with('destroy', 'Data Berhasil Dihapus!');
    }
}

resources/views/admin/data-gejala/create.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="mx-5 my-5">
    <a href="{{ route('data-gejala.index') }}" class="text-secondary">
        <h6 class="m-0 font-weight-bold"><i class="fas fa-chevron-left"></i> Kembali</h6>
    </a>
</div>

<div class="card shadow mt-3 mx-5">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tambah Data Gejala</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('data-gejala.store') }}" method="post">
            @csrf
            
            <div class="form-group">
                <label for="kode_gejala">Kode Gejala</label>
                <input type="text" class="form-control @error('kode_gejala') is-invalid @enderror" id="kode_gejala" name="kode_gejala" value="{{ old('kode_gejala') }}" placeholder="Masukkan Kode Gejala" required>
                @error('kode_gejala')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="nama_gejala">Nama Gejala</label>
                <input type="text" class="form-control @error('nama_gejala') is-invalid @enderror" id="nama_gejala" name="nama_gejala" value="{{ old('nama_gejala') }}" placeholder="Masukkan Nama Gejala" required>
                @error('nama_gejala')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            
            <button type="submit" class="btn btn-primary ">Simpan</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/data-gejala/edit.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="mx-5 my-5">
    <a href="{{ route('data-gejala.index') }}" class="text-secondary">
        <h6 class="m-0 font-weight-bold"><i class="fas fa-chevron-left"></i> Kembali</h6>
    </a>
</div>

<div class="card shadow mt-3 mx-5">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Update Data Gejala</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('data-gejala.update', $dataGejala->id) }}" method="post">
            @csrf
            @method('put')
            
            <div class="form-group">
                <label for="kode_gejala">Kode Gejala</label>
                <input type="text" class="form-control @error('kode_gejala') is-invalid @enderror" id="kode_gejala" name="kode_gejala" value="{{ old('kode_gejala', $dataGejala->kode_gejala) }}" placeholder="Masukkan Kode Gejala" required>
                @error('kode_gejala')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="nama_gejala">Nama Gejala</label>
                <input type="text" class="form-control @error('nama_gejala') is-invalid @enderror" id="nama_gejala" name="nama_gejala" value="{{ old('nama_gejala', $dataGejala->nama_gejala) }}" placeholder="Masukkan Nama Gejala" required>
                @error('nama_gejala')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            
            <button type="submit" class="btn btn-primary ">Simpan</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/data-gejala/index.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="container-fluid">

    <h1 class="h3 mb-3 text-gray-800">Data Gejala</h1>

    {{-- alert --}}
    @include('admin.alerts.alert')

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a href="{{ route('data-gejala.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Data
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Kode Gejala</th>
                            <th>Nama Gejala</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($dataGejala as $item)
                            <tr>
                                <td>{{ $loop->iteration }}.</td>
                                <td>{{ $item->kode_gejala }}</td>
                                <td>{{ $item->nama_gejala }}</td>
                                <td>
                                    <a href="{{ route('data-gejala.edit', $item->id) }}" class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm rounded-circle border-0">
                                        <i class="fas fa-pen fa-sm text-white-100"></i>
                                    </a>
                                    <form class="d-inline" action="{{ route('data-gejala.destroy', $item->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger btn-sm rounded-circle border-0" onclick="return confirm('Apakah anda yakin ?')"><i class="fas fa-trash fa-sm text-white-100"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@endsection