routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\DataArtikelController;
use App\Http\Controllers\DataGejalaController;
use App\Http\Controllers\DataJadwalPeriksaController;
use App\Http\Controllers\DataPenyakitController;
use App\Http\Controllers\DataRiwayatDiagnosaController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function(){
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'store'])->name('store');
});

Route::middleware(['auth', 'isAdmin'])->group(function(){
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/', BerandaController::class)->name('beranda');

    Route::group(['prefix' => 'data-penyakit', 'as' => 'data-penyakit.'], function() {
        Route::get('/', [DataPenyakitController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataPenyakitController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataPenyakitController::class, 'store'])->name('store');
        Route::get('/{dataPenyakit}/edit', [DataPenyakitController::class, 'edit'])->name('edit');
        Route::put('/{dataPenyakit}/edit', [DataPenyakitController::class, 'update'])->name('update');
        Route::delete('/{dataPenyakit}/delete', [DataPenyakitController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-gejala', 'as' => 'data-gejala.'], function(){
        Route::get('/', [DataGejalaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataGejalaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataGejalaController::class, 'store'])->name('store');
        Route::get('/{dataGejala}/edit', [DataGejalaController::class, 'edit'])->name('edit');
        Route::put('/{dataGejala}/edit', [DataGejalaController::class, 'update'])->name('update');
        Route::delete('/{dataGejala}/delete', [DataGejalaController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-jadwal-periksa', 'as' => 'data-jadwal-periksa.'], function() {
        Route::get('/', [DataJadwalPeriksaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataJadwalPeriksaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataJadwalPeriksaController::class, 'store'])->name('store');
        Route::delete('/{dataJadwalPeriksa}/delete', [DataJadwalPeriksaController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-riwayat-diagnosa', 'as' => 'data-riwayat-diagnosa.'], function() {
        Route::get('/', [DataRiwayatDiagnosaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataRiwayatDiagnosaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataRiwayatDiagnosaController::class, 'store'])->name('store');
        Route::get('/{dataRiwayatDiagnosa}/detail', [DataRiwayatDiagnosaController::class, 'show'])->name('show');
        Route::get('/{dataRiwayatDiagnosa}/pdf', [DataRiwayatDiagnosaController::class, 'pdf'])->name('pdf');
    });

    Route::group(['prefix' => 'data-artikel', 'as' => 'data-artikel.'], function() {
        Route::get('/', [DataArtikelController::class, 'index'])->name('index');
        Route::get('/create', [DataArtikelController::class, 'create'])->name('create');
        Route::post('/create', [DataArtikelController::class, 'store'])->name('store');
        Route::get('/{dataArtikel}/edit', [DataArtikelController::class, 'edit'])->name('edit');
        Route::put('/{dataArtikel}/edit', [DataArtikelController::class, 'update'])->name('update');
        Route::delete('/{dataArtikel}/delete', [DataArtikelController::class, 'destroy'])->name('destroy');
    });
});

app/Models/DataPenyakit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DataPenyakit extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
    protected $table = 'data_penyakit';
}

app/Http/Controllers/DataPenyakitController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DataPenyakitRequest;
use App\Models\DataPenyakit;
use Illuminate\Http\Request;

class DataPenyakitController extends Controller
{
    public function index()
    {
        $dataPenyakit = DataPenyakit::latest()->get();

        return view('admin.data-penyakit.index', compact('dataPenyakit'));
    }

    public function create()
    {
        return view('admin.data-penyakit.create');
    }

    public function store(DataPenyakitRequest $request)
    {
        DataPenyakit::create($request->all());

        return redirect()->route('data-penyakit.index')->with('success', 'Data Berhasil Ditambahkan!');
    }

    public function edit(DataPenyakit $dataPenyakit)
    {
        return view('admin.data-penyakit.edit', compact('dataPenyakit'));
    }

    public function update(DataPenyakitRequest $request, DataPenyakit $dataPenyakit)
    {
        $dataPenyakit->update($request->all());

        return redirect()->route('data-penyakit.index')->with('update', 'Data Berhasil Diupdate!');
    }

    public function destroy(DataPenyakit $dataPenyakit)
    {
        $dataPenyakit->delete();

        return redirect()->route('data-penyakit.index')->with('destroy', 'Data Berhasil Dihapus!');
    }
}

resources/views/admin/data-penyakit/create.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="mx-5 my-5">
    <a href="{{ route('data-penyakit.index') }}" class="text-secondary">
        <h6 class="m-0 font-weight-bold"><i class="fas fa-chevron-left"></i> Kembali</h6>
    </a>
</div>

<div class="card shadow mt-3 mx-5">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tambah Data Penyakit</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('data-penyakit.store') }}" method="post">
            @csrf
            
            <div class="form-group">
                <label for="kode_penyakit">Kode Penyakit</label>
                <input type="text" class="form-control @error('kode_penyakit') is-invalid @enderror" id="kode_penyakit" name="kode_penyakit" value="{{ old('kode_penyakit') }}" placeholder="Masukkan Kode Penyakit" required>
                @error('kode_penyakit')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="nama_penyakit">Nama Penyakit</label>
                <input type="text" class="form-control @error('nama_penyakit') is-invalid @enderror" id="nama_penyakit" name="nama_penyakit" value="{{ old('nama_penyakit') }}" placeholder="Masukkan Nama Penyakit" required>
                @error('nama_penyakit')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="deskripsi">Deskripsi</label>
                <textarea id="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" name="deskripsi" rows="4" cols="50" placeholder="Masukkan Deskripsi">{{ old('deskripsi') }}</textarea>
                @error('deskripsi')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="pengobatan">Pengobatan</label>
                <textarea id="pengobatan" class="form-control @error('pengobatan') is-invalid @enderror" name="pengobatan" rows="4" cols="50" placeholder="Masukkan Pengobatan">{{ old('pengobatan') }}</textarea>
                @error('pengobatan')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            
            <button type="submit" class="btn btn-primary ">Simpan</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/data-penyakit/edit.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="mx-5 my-5">
    <a href="{{ route('data-penyakit.index') }}" class="text-secondary">
        <h6 class="m-0 font-weight-bold"><i class="fas fa-chevron-left"></i> Kembali</h6>
    </a>
</div>

<div class="card shadow mt-3 mx-5">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Update Data Penyakit</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('data-penyakit.update', $dataPenyakit->id) }}" method="post">
            @csrf
            @method('put')
            
            <div class="form-group">
                <label for="kode_penyakit">Kode Penyakit</label>
                <input type="text" class="form-control @error('kode_penyakit') is-invalid @enderror" id="kode_penyakit" name="kode_penyakit" value="{{ old('kode_penyakit', $dataPenyakit->kode_penyakit) }}" placeholder="Masukkan Kode Penyakit" required>
                @error('kode_penyakit')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="nama_penyakit">Nama Penyakit</label>
                <input type="text" class="form-control @error('nama_penyakit') is-invalid @enderror" id="nama_penyakit" name="nama_penyakit" value="{{ old('nama_penyakit', $dataPenyakit->nama_penyakit) }}" placeholder="Masukkan Nama Penyakit" required>
                @error('nama_penyakit')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="deskripsi">Deskripsi</label>
                <textarea id="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" name="deskripsi" rows="4" cols="50" placeholder="Masukkan Deskripsi">{{ old('deskripsi', $dataPenyakit->deskripsi) }}</textarea>
                @error('deskripsi')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="pengobatan">Pengobatan</label>
                <textarea id="pengobatan" class="form-control @error('pengobatan') is-invalid @enderror" name="pengobatan" rows="4" cols="50" placeholder="Masukkan Pengobatan">{{ old('pengobatan', $dataPenyakit->pengobatan) }}</textarea>
                @error('pengobatan')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            
            <button type="submit" class="btn btn-primary ">Simpan</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/data-penyakit/index.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="container-fluid">

    <h1 class="h3 mb-3 text-gray-800">Data Penyakit</h1>

    {{-- alert --}}
    @include('admin.alerts.alert')

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a href="{{ route('data-penyakit.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Data
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Kode Penyakit</th>
                            <th>Nama Penyakit</th>
                            <th>Deskripsi</th>
                            <th>Pengobatan</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($dataPenyakit as $item)
                            <tr>
                                <td>{{ $loop->iteration }}.</td>
                                <td>{{ $item->kode_penyakit }}</td>
                                <td>{{ $item->nama_penyakit }}</td>
                                <td>{{ $item->deskripsi }}</td>
                                <td>{{ $item->pengobatan }}</td>
                                <td>
                                    <a href="{{ route('data-penyakit.edit', $item->id) }}" class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm rounded-circle border-0">
                                        <i class="fas fa-pen fa-sm text-white-100"></i>
                                    </a>
                                    <form class="d-inline" action="{{ route('data-penyakit.destroy', $item->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger btn-sm rounded-circle border-0" onclick="return confirm('Apakah anda yakin ?')"><i class="fas fa-trash fa-sm text-white-100"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@endsection