routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\DataArtikelController;
use App\Http\Controllers\DataGejalaController;
use App\Http\Controllers\DataJadwalPeriksaController;
use App\Http\Controllers\DataPenyakitController;
use App\Http\Controllers\DataRiwayatDiagnosaController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function(){
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'store'])->name('store');
});

Route::middleware(['auth', 'isAdmin'])->group(function(){
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/', BerandaController::class)->name('beranda');

    Route::group(['prefix' => 'data-penyakit', 'as' => 'data-penyakit.'], function() {
        Route::get('/', [DataPenyakitController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataPenyakitController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataPenyakitController::class, 'store'])->name('store');
        Route::get('/{dataPenyakit}/edit', [DataPenyakitController::class, 'edit'])->name('edit');
        Route::put('/{dataPenyakit}/edit', [DataPenyakitController::class, 'update'])->name('update');
        Route::delete('/{dataPenyakit}/delete', [DataPenyakitController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-gejala', 'as' => 'data-gejala.'], function(){
        Route::get('/', [DataGejalaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataGejalaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataGejalaController::class, 'store'])->name('store');
        Route::get('/{dataGejala}/edit', [DataGejalaController::class, 'edit'])->name('edit');
        Route::put('/{dataGejala}/edit', [DataGejalaController::class, 'update'])->name('update');
        Route::delete('/{dataGejala}/delete', [DataGejalaController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-jadwal-periksa', 'as' => 'data-jadwal-periksa.'], function() {
        Route::get('/', [DataJadwalPeriksaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataJadwalPeriksaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataJadwalPeriksaController::class, 'store'])->name('store');
        Route::delete('/{dataJadwalPeriksa}/delete', [DataJadwalPeriksaController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-riwayat-diagnosa', 'as' => 'data-riwayat-diagnosa.'], function() {
        Route::get('/', [DataRiwayatDiagnosaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataRiwayatDiagnosaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataRiwayatDiagnosaController::class, 'store'])->name('store');
        Route::get('/{dataRiwayatDiagnosa}/detail', [DataRiwayatDiagnosaController::class, 'show'])->name('show');
        Route::get('/{dataRiwayatDiagnosa}/pdf', [DataRiwayatDiagnosaController::class, 'pdf'])->name('pdf');
    });

    Route::group(['prefix' => 'data-artikel', 'as' => 'data-artikel.'], function() {
        Route::get('/', [DataArtikelController::class, 'index'])->name('index');
        Route::get('/create', [DataArtikelController::class, 'create'])->name('create');
        Route::post('/create', [DataArtikelController::class, 'store'])->name('store');
        Route::get('/{dataArtikel}/edit', [DataArtikelController::class, 'edit'])->name('edit');
        Route::put('/{dataArtikel}/edit', [DataArtikelController::class, 'update'])->name('update');
        Route::delete('/{dataArtikel}/delete', [DataArtikelController::class, 'destroy'])->name('destroy');
    });
});

resources/views/admin/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin</title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('template-admin/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('template-admin/css/sb-admin-2.min.css') }}" rel="stylesheet">

    <!-- data table -->
    <link href="{{ asset('template-admin/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
            @include('admin.layouts.sidebar')
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <h4 style="margin: 0; font-weight: 600;" class="text-dark">Sistem Pakar Untuk Diagnosis Penyakit Pada Kucing</h4>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600">{{ auth()->user()->nama }}</span>
                                <img class="img-profile rounded-circle" src="{{ asset('template-admin/img/undraw_profile.svg') }}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <form action="{{ route('logout') }}" method="post">
                                    @csrf
                                    <button class="dropdown-item" type="submit"> <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>Logout</button>
                                </form>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    {{-- content here --}}
                    @yield('content')

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('template-admin/vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('template-admin/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ asset('template-admin/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ asset('template-admin/js/sb-admin-2.min.js') }}"></script>

    <!-- Page level plugins -->
    <script src="{{ asset('template-admin/vendor/chart.js/Chart.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('template-admin/js/demo/chart-area-demo.js') }}"></script>
    <script src="{{ asset('template-admin/js/demo/chart-pie-demo.js') }}"></script>

    {{-- data table --}}
    <script src="{{ asset('template-admin/vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('template-admin/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('template-admin/js/demo/datatables-demo.js') }}"></script>

    @stack('script')

</body>

</html>

resources/views/admin/layouts/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    {{-- <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a> --}}
    <div class="mt-5 mb-3"></div>

    <hr class="sidebar-divider my-0">

    <li class="nav-item {{ request()->is('/*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('beranda') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Beranda</span>
        </a>
    </li>
    <li class="nav-item {{ request()->is('data-penyakit*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('data-penyakit.index') }}">
            <i class="fas fa-fw fa-folder"></i>
            <span>Data Penyakit</span>
        </a>
    </li>
    <li class="nav-item {{ request()->is('data-gejala*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('data-gejala.index') }}">
            <i class="fas fa-fw fa-folder"></i>
            <span>Data Gejala</span>
        </a>
    </li>
    <li class="nav-item {{ request()->is('data-jadwal-periksa*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('data-jadwal-periksa.index') }}">
            <i class="fas fa-fw fa-folder"></i>
            <span>Data Jadwal Periksa</span>
        </a>
    </li>
    <li class="nav-item {{ request()->is('data-riwayat-diagnosa*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('data-riwayat-diagnosa.index') }}">
            <i class="fas fa-fw fa-folder"></i>
            <span>Data Riwayat Diagnosa</span>
        </a>
    </li>
    <li class="nav-item {{ request()->is('data-artikel*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('data-artikel.index') }}">
            <i class="fas fa-fw fa-folder"></i>
            <span>Data Artikel</span>
        </a>
    </li>

</ul>