routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\DataArtikelController;
use App\Http\Controllers\DataGejalaController;
use App\Http\Controllers\DataJadwalPeriksaController;
use App\Http\Controllers\DataPenyakitController;
use App\Http\Controllers\DataRiwayatDiagnosaController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function(){
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'store'])->name('store');
});

Route::middleware(['auth', 'isAdmin'])->group(function(){
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/', BerandaController::class)->name('beranda');

    Route::group(['prefix' => 'data-penyakit', 'as' => 'data-penyakit.'], function() {
        Route::get('/', [DataPenyakitController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataPenyakitController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataPenyakitController::class, 'store'])->name('store');
        Route::get('/{dataPenyakit}/edit', [DataPenyakitController::class, 'edit'])->name('edit');
        Route::put('/{dataPenyakit}/edit', [DataPenyakitController::class, 'update'])->name('update');
        Route::delete('/{dataPenyakit}/delete', [DataPenyakitController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-gejala', 'as' => 'data-gejala.'], function(){
        Route::get('/', [DataGejalaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataGejalaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataGejalaController::class, 'store'])->name('store');
        Route::get('/{dataGejala}/edit', [DataGejalaController::class, 'edit'])->name('edit');
        Route::put('/{dataGejala}/edit', [DataGejalaController::class, 'update'])->name('update');
        Route::delete('/{dataGejala}/delete', [DataGejalaController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-jadwal-periksa', 'as' => 'data-jadwal-periksa.'], function() {
        Route::get('/', [DataJadwalPeriksaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataJadwalPeriksaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataJadwalPeriksaController::class, 'store'])->name('store');
        Route::delete('/{dataJadwalPeriksa}/delete', [DataJadwalPeriksaController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'data-riwayat-diagnosa', 'as' => 'data-riwayat-diagnosa.'], function() {
        Route::get('/', [DataRiwayatDiagnosaController::class, 'index'])->name('index');
        Route::get('/tambah-data', [DataRiwayatDiagnosaController::class, 'create'])->name('create');
        Route::post('/tambah-data', [DataRiwayatDiagnosaController::class, 'store'])->name('store');
        Route::get('/{dataRiwayatDiagnosa}/detail', [DataRiwayatDiagnosaController::class, 'show'])->name('show');
        Route::get('/{dataRiwayatDiagnosa}/pdf', [DataRiwayatDiagnosaController::class, 'pdf'])->name('pdf');
    });

    Route::group(['prefix' => 'data-artikel', 'as' => 'data-artikel.'], function() {
        Route::get('/', [DataArtikelController::class, 'index'])->name('index');
        Route::get('/create', [DataArtikelController::class, 'create'])->name('create');
        Route::post('/create', [DataArtikelController::class, 'store'])->name('store');
        Route::get('/{dataArtikel}/edit', [DataArtikelController::class, 'edit'])->name('edit');
        Route::put('/{dataArtikel}/edit', [DataArtikelController::class, 'update'])->name('update');
        Route::delete('/{dataArtikel}/delete', [DataArtikelController::class, 'destroy'])->name('destroy');
    });
});

app/Models/DataArtikel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DataArtikel extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
    protected $table = 'data_artikel';
}

app/Http/Controllers/DataArtikelController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DataArtikelRequest;
use App\Models\DataArtikel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class DataArtikelController extends Controller
{
    public function index()
    {
        $dataArtikel = DataArtikel::latest()->get();

        return view('admin.data-artikel.index', compact('dataArtikel'));
    }

    public function create()
    {
        return view('admin.data-artikel.create');
    }

    public function store(DataArtikelRequest $request)
    {
        $gambar = $request->file('gambar');
        $nama_gambar = time()."_".$gambar->getClientOriginalName();
        $gambar->storeAs('public/images', $nama_gambar);

        DataArtikel::create([
            'judul_artikel' => $request->judul_artikel,
            'deskripsi' => $request->deskripsi,
            'gambar' => $nama_gambar
        ]);

        return redirect()->route('data-artikel.index')->with('success', 'Data Berhasil Ditambahkan!');
    }

    public function edit(DataArtikel $dataArtikel)
    {
        return view('admin.data-artikel.edit', compact('dataArtikel'));
    }

    public function update(DataArtikelRequest $request, DataArtikel $dataArtikel)
    {   
        $dataArtikel->update($request->all());

        if($request->hasFile('gambar')){
            Storage::delete('public/images/'.$dataArtikel->gambar);
            $gambar = $request->file('gambar');
            $nama_gambar = time()."_".$gambar->getClientOriginalName();
            $gambar->storeAs('public/images', $nama_gambar);
            $dataArtikel->gambar = $nama_gambar;
            $dataArtikel->update();            
        }

        return redirect()->route('data-artikel.index')->with('update', 'Data Berhasil Diupdate!');
    }

    public function destroy(DataArtikel $dataArtikel)
    {
        $dataArtikel->delete();
        Storage::delete('public/images/'.$dataArtikel->gambar);

        return redirect()->route('data-artikel.index')->with('destroy', 'Data Berhasil Dihapus!');
    }
}

resources/views/admin/data-artikel/create.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="mx-5 my-5">
    <a href="{{ route('data-artikel.index') }}" class="text-secondary">
        <h6 class="m-0 font-weight-bold"><i class="fas fa-chevron-left"></i> Kembali</h6>
    </a>
</div>

<div class="card shadow mt-3 mx-5">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tambah Data Artikel</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('data-artikel.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            
            <div class="form-group">
                <label for="judul_artikel">Judul Artikel</label>
                <input type="text" class="form-control @error('judul_artikel') is-invalid @enderror" id="judul_artikel" name="judul_artikel" value="{{ old('judul_artikel') }}" placeholder="Masukkan Judul Artikel" required>
                @error('judul_artikel')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="deskripsi">Deskripsi</label>
                <textarea id="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" name="deskripsi" rows="4" cols="50" placeholder="Masukkan Deskripsi">{{ old('deskripsi') }}</textarea>
                @error('deskripsi')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group pt-3">
                <label for="gambar">Gambar</label>
                <input type="file" class=" @error('gambar') is-invalid @enderror" id="gambar" name="gambar" required onchange="previewImage()">
                @error('gambar')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <img src="" alt="" class="img-preview mb-3" width="300px">
            
            <button type="submit" class="btn btn-primary ">Simpan</button>
        </form>
    </div>
</div>
@endsection

@push('script')
    <script>
        // preview image
        function previewImage() {
            const image = document.querySelector('#gambar');
            const imgPreview = document.querySelector('.img-preview');

            imgPreview.style.display = 'block';

            const oFReader = new FileReader();
            oFReader.readAsDataURL(image.files[0]);

            oFReader.onload = function(oFREvent) {
                imgPreview.src = oFREvent.target.result;
            }
        }
    </script>
@endpush

resources/views/admin/data-artikel/edit.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="mx-5 my-5">
    <a href="{{ route('data-artikel.index') }}" class="text-secondary">
        <h6 class="m-0 font-weight-bold"><i class="fas fa-chevron-left"></i> Kembali</h6>
    </a>
</div>

<div class="card shadow mt-3 mx-5">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Tambah Data Artikel</h6>
    </div>
    <div class="card-body">
        <form action="{{ route('data-artikel.update', $dataArtikel->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('put')
            
            <div class="form-group">
                <label for="judul_artikel">Judul Artikel</label>
                <input type="text" class="form-control @error('judul_artikel') is-invalid @enderror" id="judul_artikel" name="judul_artikel" value="{{ old('judul_artikel', $dataArtikel->judul_artikel) }}" placeholder="Masukkan Judul Artikel" required>
                @error('judul_artikel')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="deskripsi">Deskripsi</label>
                <textarea id="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" name="deskripsi" rows="4" cols="50" placeholder="Masukkan Deskripsi">{{ old('deskripsi', $dataArtikel->deskripsi) }}</textarea>
                @error('deskripsi')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group pt-3">
                <label for="gambar">Gambar</label>
                <input type="file" class=" @error('gambar') is-invalid @enderror" id="gambar" name="gambar" onchange="previewImage()" value="{{ old('gambar', $dataArtikel->gambar) }}">
                @error('gambar')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <img src="{{ asset('storage/images/'.$dataArtikel->gambar) }}" alt="" class="d-block img-preview mb-3" width="300px">
            
            <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
</div>
@endsection

@push('script')
    <script>
        // preview image
        function previewImage() {
            const image = document.querySelector('#gambar');
            const imgPreview = document.querySelector('.img-preview');

            imgPreview.style.display = 'block';

            const oFReader = new FileReader();
            oFReader.readAsDataURL(image.files[0]);

            oFReader.onload = function(oFREvent) {
                imgPreview.src = oFREvent.target.result;
            }
        }
    </script>
@endpush

resources/views/admin/data-artikel/index.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="container-fluid">

    <h1 class="h3 mb-3 text-gray-800">Data Artikel</h1>

    {{-- alert --}}
    @include('admin.alerts.alert')

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a href="{{ route('data-artikel.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Data
            </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Judul Artikel</th>
                            <th>Deskripsi</th>
                            <th>Gambar</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($dataArtikel as $item)
                            <tr>
                                <td>{{ $loop->iteration }}.</td>
                                <td>{{ $item->judul_artikel }}</td>
                                <td>{{ $item->deskripsi }}</td>
                                <td><img src="{{ asset('storage/images/'.$item->gambar) }}" alt="gambar" width="200px"></td>
                                <td>
                                    <a href="{{ route('data-artikel.edit', $item->id) }}" class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm rounded-circle border-0">
                                        <i class="fas fa-pen fa-sm text-white-100"></i>
                                    </a>
                                    <form class="d-inline" action="{{ route('data-artikel.destroy', $item->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger btn-sm rounded-circle border-0" onclick="return confirm('Apakah anda yakin ?')"><i class="fas fa-trash fa-sm text-white-100"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@endsection